### ISSUE TITLE
PhealNg got updated

### ISSUE THREAD

**Issue by Bavragor** [tarioch/eveapi-fetcher-bundle#13]
PhealNg got updated and uses now Guzzle in order to communicate, could there be any problems with that ?

**Comment by okwinza** [comment]
Its about time PhealNG moved from its own curl wrapper to something more decent.
I haven't noticed any BC breaks as it is pretty much internal change so i don't think anything would change from user perspective.

**Comment by tarioch** [comment]
Don't see a problem with that, but this reminds me that I want to change the binding from my own symfony pheal binding to another one: https://github.com/tarioch/pheal-bundle/issues/1

**Comment by Bavragor** [comment]
Yeah I did the changes on PhealNG about the curl stuff ^^ but I wasn't sure anymore and just want to mentioned it
